language: python
cache: pip

python:
  - 2.7
  - 3.6
env:
  - LEKTOR=2.3
  - LEKTOR=3.0
  - LEKTOR=3.1
  - LEKTOR=master

matrix:
  exclude:
    - python: 3.6
      env: LEKTOR=2.3

install:
  - pip install -U virtualenv setuptools
  - if [[ "${LEKTOR}" = "master" ]]; then pip install "git+https://github.com/lektor/lektor.git"; else pip install "lektor==${LEKTOR}"; fi

script:
  - tests/test.sh

notifications:
  email: false
